name: NDVI
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - boost-cpp=1.74.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cairo=1.16.0
  - certifi=2020.12.5
  - cfitsio=3.470
  - curl=7.77.0
  - expat=2.4.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - freexl=1.0.6
  - gdal=3.1.4
  - geos=3.9.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - hdf4=4.2.15
  - hdf5=1.10.6
  - icu=68.1
  - jbig=2.1
  - jpeg=9d
  - json-c=0.15
  - kealib=1.4.14
  - krb5=1.19.1
  - ld_impl_linux-64=2.33.1
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.77.0
  - libdap4=3.20.6
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgdal=3.1.4
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.68.2
  - libgomp=9.3.0
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.15
  - libpng=1.6.37
  - libpq=13.3
  - librttopo=1.1.0
  - libspatialite=5.0.1
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxml2=2.9.12
  - libzip=1.7.3
  - lz4-c=1.9.3
  - ncurses=6.2
  - numpy=1.20.3
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - pcre=8.44
  - pip=21.1.1
  - pixman=0.40.0
  - poppler=21.03.0
  - poppler-data=0.4.10
  - postgresql=13.3
  - proj=8.0.0
  - pthread-stubs=0.4
  - python=3.8.10
  - python_abi=3.8
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.35.5
  - tiledb=2.2.9
  - tk=8.6.10
  - tzcode=2021a
  - tzdata=2021a
  - wheel=0.36.2
  - xerces-c=3.2.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - affine==2.3.0
    - attrs==21.2.0
    - click==7.1.2
    - click-plugins==1.1.1
    - cligj==0.7.1
    - osgeo==0.0.0
    - pandas==1.2.4
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2021.1
    - rasterio==1.2.3
    - six==1.16.0
    - snuggs==1.4.7
