apiVersion: v1
kind: ServiceAccount
metadata:
  name: geodata-launcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{.Release.namespace}}
  name: agent-create
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{.Release.namespace}}
  name: agent-watch
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/status"]
  verbs: ["watch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: watch-pods
  namespace: {{.Release.namespace}}
subjects:
- kind: ServiceAccount
  name: geodata-launcher
  namespace: {{.Release.namespace}}
roleRef:
  kind: Role
  name: agent-watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: launch-jobs
  namespace: {{.Release.namespace}}
subjects:
- kind: ServiceAccount
  name: geodata-launcher
  namespace: {{.Release.namespace}}
roleRef:
  kind: Role
  name: agent-create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kube-system
  name: {{ include "geodata_release.name" . }}-agent-system
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods"]
  verbs: ["get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "geodata_release.name" . }}-check-namespaces
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: geodata-launcher
  namespace: {{.Release.namespace}}
roleRef:
  kind: Role
  name: agent-system
