apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prefect-agent
  name: prefect-agent
  namespace: {{.Release.namespace}}
spec:
  replicas: {{ .Values.prefect.replicas }}
  selector:
    matchLabels:
      app: prefect-agent
  template:
    metadata:
      labels:
        app: prefect-agent
    spec:
      containers:
      - command:
        - prefect
        - worker
        - start
        - -p
        - {{.Values.prefect.workPool}}
        env:
        - name: PREFECT_API_URL
          value: {{.Values.prefect.apiURL}}
        - name: PREFECT_API_KEY
          value: {{.Values.prefect.apiKey}}
        image: {{.Values.workerContainer}}
        imagePullPolicy: IfNotPresent
        name: agent
      serviceAccountName: geodata-launcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prefect-agent
  namespace: {{.Release.namespace}}
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - pods/log
  - pods/status
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prefect-agent-role-binding
  namespace: {{.Release.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prefect-agent
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{.Release.namespace}}

