apiVersion: v1
kind: ServiceAccount
metadata:
  name: geodata-launcher
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{.Release.Namespace}}
  name: geodata-prefect-agent
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/status"]
  verbs: ["watch", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: launch-jobs
  namespace: {{.Release.Namespace}}
subjects:
- kind: ServiceAccount
  name: geodata-launcher
  namespace: {{.Release.Namespace}}
roleRef:
  kind: Role
  name: geodata-prefect-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kube-system
  name: {{ include "geodata_release.name" . }}-agent-system
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "geodata_release.name" . }}-check-namespaces
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: geodata-launcher
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "geodata_release.name" . }}-agent-system
