kind: ServiceAccount
apiVersion: v1
metadata:
  name: dask-job
 
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dask-job
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods/log"]
  verbs: ["get", "list"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dask-job
subjects:
- kind: ServiceAccount
  name: dask-job
roleRef:
  kind: Role
  name: dask-job
  apiGroup: rbac.authorization.k8s.io
