apiVersion: v1
kind: PersistentVolume
metadata:
  name: nova-geodata-prod-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /sciclone/nova/test
    server: 128.239.59.130
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nova-geodata-prod
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
