apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  namespace: {{.Values.namespace}} 
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  hostPath:
    path: /data/pv0001/

