raw_dir = "/sciclone/nova/REU/geo/geoquery/staging/data/raw/gemdata_201708"
output_dir = "/sciclone/nova/REU/geo/geoquery/staging/data/datasets/gemdata_201708"

pixel_size = 0.01

overwrite_binary_raster = false
overwrite_distance_raster = false


[run]
max_workers = 1
log_dir = "/sciclone/nova/REU/geo/geoquery/staging/data/datasets/gemdata_201708/logs"


[repo]
url = "https://github.com/aiddata/geo-datasets.git"
branch = "master"
directory = "datasets/gem"


[deploy]
deployment_name = "gem"
image_tag = "148bd36"
version = 11
flow_file_name = "main"
flow_name = "gem"
work_pool = "geodata"
