raw_dir = "/sciclone/nova/REU/geo/geoquery/staging/data/raw/accessibility_map"
output_dir = "/sciclone/nova/REU/geo/geoquery/staging/data/datasets/access_50k"

overwrite_download = false
overwrite_process = true


[run]
max_workers = 1
log_dir = "/sciclone/nova/REU/geo/geoquery/staging/data/datasets/access_50k/logs"


[repo]
url = "https://github.com/aiddata/geo-datasets.git"
branch = "master"
directory = "datasets/accessibility_map"


[deploy]
deployment_name = "accessibility_map"
image_tag = "083d531"
version = 1
flow_file_name = "main"
flow_name = "accessibility_map"
work_pool = "geodata"
