raw_dir = "/sciclone/aiddata10/REU/geo/raw/gpm"
output_dir = "/sciclone/aiddata10/REU/geo/data/rasters/gpm"

email = "<ADD YOUR EMAIL>"
version = "v07b"
years = [ 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023 ]
year_agg_method = "mean"
overwrite_downloads = false
verify_existing_downloads = false
overwrite_processing = false


[run]
run_parallel = false
max_workers = 1
log_dir = "/sciclone/aiddata10/REU/geo/raw/gpm/logs"


[repo]
url = "https://github.com/aiddata/geo-datasets.git"
branch = "master"
directory = "datasets/gpm"


[deploy]
deployment_name = "GPM"
image_tag = "05dea6e"
version = 2
flow_file_name = "main"
flow_name = "gpm"
work_pool = "geodata-pool"
data_manager_version = "0.4.0"
