version = "v6"
gb_web_hash = "57dcd43"

dl_iso3_list = ["AFG", "GHA", "ETH", "HND"]

output_dir = "/sciclone/nova/REU/geo/geoquery/staging/boundaries/geoboundaries"

skip_existing = true


[run]
max_workers = 1
log_dir = "/sciclone/nova/REU/geo/geoquery/staging/boundaries/geoboundaries/logs"


[repo]
url = "https://github.com/aiddata/geo-datasets.git"
branch = "master"
directory = "datasets/geoboundaries"


[deploy]
deployment_name = "geoBoundaries"
image_tag = "01654d2"
version = 5
flow_file_name = "main"
flow_name = "geoBoundariesDownloadFlow"
work_pool = "geodata"
