version = "v6"
gb_data_hash = "9469f09"
gb_web_hash = "57dcd43"

dl_iso3_list = []

output_dir = "/sciclone/aiddata10/REU/geo/data/boundaries/geoboundaries"

overwrite_existing = false


[run]
max_workers = 1
log_dir = "/sciclone/aiddata10/REU/geo/data/boundaries/geoboundaries/logs"


[repo]
url = "https://github.com/aiddata/geo-datasets.git"
branch = "master"
directory = "datasets/geoboundaries"


[deploy]
deployment_name = "geoBoundaries"
image_tag = "05dea6e"
version = 2
flow_file_name = "main"
flow_name = "geoBoundariesFlow"
work_pool = "geodata-pool"
data_manager_version = "0.4.0"
