# change var - set to intended output directories
raw_dir = "/sciclone/aiddata10/REU/geo/raw/distance_to/water"
output_dir = "/sciclone/aiddata10/REU/geo/data/rasters/distance_to/water"
gshhg_version = "2.3.7"
ne_hash = "d4533efe3715c55b51f49bc2bde9694bff2bf7b1"
overwrite_download = false
overwrite_extract = false
overwrite_binary_raster = false
overwrite_distance_raster = false
pixel_size = 0.01
download_files = [ "http://www.soest.hawaii.edu/pwessel/gshhg/gshhg-shp-2.3.7.zip", "https://github.com/nvkelso/natural-earth-vector/archive/d4533efe3715c55b51f49bc2bde9694bff2bf7b1.zip" ]
raster_type = [ "binary", "distance" ]


[run]
max_workers = 12
# cores_per_process only used for dask-jobqueue runs (backend=prefect, task_runner=hpc)
cores_per_process = 2
log_dir = "/sciclone/aiddata10/REU/geo/data/rasters/distance_to_water/logs"


[repo]
url = "https://github.com/aiddata/geo-datasets.git"
branch = "master"
directory = "datasets/distance_to_water"


[deploy]
deployment_name = "distance_to_water"
image_tag = "05dea6e"
version = 2
flow_file_name = "main"
flow_name = "distance_to_water"
work_pool = "geodata-pool"
data_manager_version = "0.4.0"
