year = "2025"
dataset = "COUNTY"

raw_dir = "/sciclone/nova/REU/geo/geoquery/staging/data/raw/tiger"
output_dir = "/sciclone/nova/REU/geo/geoquery/staging/data/boundaries/tiger"

overwrite_download = false
overwrite_process = false


[run]
max_workers = 1
log_dir = "/sciclone/nova/REU/geo/geoquery/staging/data/raw/tiger/logs"


[repo]
url = "https://github.com/aiddata/geo-datasets.git"
branch = "master"
directory = "datasets/tiger"


[deploy]
deployment_name = "tiger"
image_tag = "083d531"
version = 10
flow_file_name = "main"
flow_name = "TIGERDownloadFlow"
work_pool = "geodata"
