raw_dir = "/sciclone/aiddata10/REU/geo/raw/pm25"
output_dir = "/sciclone/aiddata10/REU/geo/data/rasters/pm25"

version = "V5GL04"
years = [ 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022 ]

overwrite_downloads = false
verify_existing_downloads = false
overwrite_processing = false


[run]
max_workers = 1
log_dir = "/sciclone/aiddata10/REU/geo/raw/pm25/logs"


[repo]
url = "https://github.com/aiddata/geo-datasets.git"
branch = "master"
directory = "datasets/pm25"


[deploy]
deployment_name = "PM25"
image_tag = "05dea6e"
version = 3
flow_file_name = "main"
flow_name = "pm25"
work_pool = "geodata-pool"
data_manager_version = "0.4.0"
