process_dir = "/tmp"
raw_dir = "/sciclone/aiddata10/REU/geo/raw/MODIS/terra/MOLT/MOD11C3.061"
output_dir = "/sciclone/aiddata10/REU/geo/data/rasters/MODIS/terra/MOLT/MOD11C3.061"
username = "<username>"
password = "<password>"
years = [ 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022 ]
overwrite_download = false
overwrite_monthly = false
overwrite_yearly = true


[run]
max_workers = 8
log_dir = "/sciclone/aiddata10/REU/geo/raw/MODIS/terra/MOLT/MOD11C3.061/logs"


[repo]
url = "https://github.com/aiddata/geo-datasets.git"
branch = "master"
directory = "datasets/modis_lst"


[deploy]
deployment_name = "modis_lst"
image_tag = "05dea6e"
version = 4
flow_file_name = "main"
flow_name = "modis_lst"
work_pool = "geodata-pool"
data_manager_version = "0.4.0"
