raw_dir = "/sciclone/nova/REU/geo/geoquery/staging/data/raw/ucdp"
output_dir = "/sciclone/nova/REU/geo/geoquery/staging/data/datasets/ucdp"

overwrite_download = false
overwrite_process = false

dataset = "ged261"

[run]
max_workers = 2
log_dir = "/sciclone/nova/REU/geo/geoquery/staging/data/raw/ucdp/logs"
backend = "prefect"

[repo]
url = "https://github.com/aiddata/geo-datasets.git"
branch = "master"
directory = "datasets/ucdp"


[deploy]
deployment_name = "ucdp"
image_tag = "083d531"
version = 10
flow_file_name = "main"
flow_name = "ucdp"
work_pool = "geodata"
