download_url = "https://datadownload-production.s3.us-east-1.amazonaws.com/WCMC_043_GlobalCH_Drilldown_IFCPS6_2025.zip"

raw_dir = "/sciclone/nova/REU/geo/geoquery/staging/data/raw/critical_habitats/2025"
output_dir = "/sciclone/nova/REU/geo/geoquery/staging/data/datasets/critical_habitats/2025"

max_retries = 5
overwrite_download = false
overwrite_output = false


[run]
max_workers = 1
log_dir = "/sciclone/nova/REU/geo/geoquery/staging/data/datasets/critical_habitats/2025/logs"


[repo]
url = "https://github.com/aiddata/geo-datasets.git"
branch = "master"
directory = "datasets/critical_habitats"


[deploy]
deployment_name = "Critical Habitats"
image_tag = "083d531"
version = 10
flow_file_name = "main"
flow_name = "critical_habitats"
work_pool = "geodata"
