username = "jacobhall"
password = "PASSWORD"

data_url = "https://oco2.gesdisc.eosdis.nasa.gov/data/OCO2_DATA/OCO2_L2_Lite_FP.11.1r/"
raw_dir = "/sciclone/aiddata10/REU/geo/raw/gesdisc/OCO2_L2_Lite_FP.11.1r/"
output_dir = "/sciclone/aiddata10/REU/geo/data/rasters/gesdisc/OCO2_L2_Lite_FP.11.1r/xco2"

overwrite_download = false
overwrite_processing = false


year_list = [ 2015, 2016, 2017, 2018, 2019, 2020, 2021 ]

# interpolation method for processing step
interp_method = "linear"

run_a = true
run_b = true
run_c = true
run_d = true
run_e = true
run_f = true
run_g = true


[run]
max_workers = 6
log_dir = "/sciclone/aiddata10/REU/geo/raw/gesdisc/OCO2_L2_Lite_FP.11.1r/logs"


[repo]
url = "https://github.com/aiddata/geo-datasets.git"
branch = "master"
directory = "oco2"


[deploy]
deployment_name = "oco2"
image_tag = "05dea6e"
version = 2
flow_file_name = "main"
flow_name = "oco2"
work_pool = "geodata-pool"
data_manager_version = "0.3.0"
