# change var = set to year range wanted
years = [ 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020 ]

# output directories
# process_dir = /local/scr/smgoodman/TMPDIR/worldpop/population_age_sex
process_dir =  "/sciclone/aiddata10/REU/geo/raw/worldpop/population_age_sex/tmp"
raw_dir = "/sciclone/aiddata10/REU/geo/raw/worldpop/population_age_sex/"
output_dir = "/sciclone/aiddata10/REU/geo/data/rasters/worldpop/population_age_sex/"

overwrite_download = false
overwrite_processing = false


[run]
max_workers = 10
log_dir = "/sciclone/aiddata10/REU/geo/raw/worldpop/population_age_sex/logs"


[repo]
url = "https://github.com/aiddata/geo-datasets.git"
branch = "master"
directory = "datasets/worldpop_age_sex"


[deploy]
deployment_name = "worldpop_age_sex"
image_tag = "05dea6e"
version = 3
flow_file_name = "main"
flow_name = "worldpop_age_sex"
work_pool = "geodata-pool"
data_manager_version = "0.4.2"
