# change var = set to year range wanted
years = [ 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020 ]

# output directories
raw_dir = "/sciclone/aiddata10/REU/geo/raw/worldpop/population_counts/1km_mosaic"
output_dir = "/sciclone/aiddata10/REU/geo/data/rasters/worldpop/population_counts/1km_mosaic"

overwrite_download = false
overwrite_processing = true


[run]
max_workers = 25
log_dir = "/sciclone/aiddata10/REU/geo/raw/worldpop/logs"


[repo]
url = "https://github.com/aiddata/geo-datasets.git"
branch = "master"
directory = "datasets/worldpop_pop_count"


[deploy]
deployment_name = "worldpop_pop_count"
image_tag = "05dea6e"
version = 2
flow_file_name = "main"
flow_name = "worldpop_pop_count"
work_pool = "geodata-pool"
data_manager_version = "0.4.0"

