# change var = set to year range wanted - range available 1989-2020
years = [ 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023 ]

# change var - set to intended output directories
raw_dir = "/sciclone/aiddata10/REU/geo/raw/plad/v70"
output_dir = "/sciclone/aiddata10/REU/geo/data/rasters/plad/v70"
max_retries = 5
overwrite_download = true
overwrite_output = true


[run]
max_workers = 1
log_dir = "/sciclone/aiddata10/REU/geo/data/rasters/plad/v70/logs"


[repo]
url = "https://github.com/aiddata/geo-datasets.git"
branch = "master"
directory = "datasets/plad"


[deploy]

deployment_name = "PLAD"
image_tag = "05dea6e"
version = 1
flow_file_name = "main"
flow_name = "plad"
work_pool = "geodata-pool"
data_manager_version = "0.3.0"
